86/prepay credits
CCI-MOC/invoicing pull request #128
Opened 2024-12-19 18:38 UTC by QuanMPhm

Closes #86. This PR consists of only the last commit, "NERC Prepay Credits...". 

Two functions have been added to the Prepayment Processor. One is to obtain the credits "snapshot". A test case has been written for this function.

2025-01-10 16:19 UTC, knikolla commented on process_report/processors/prepayment_processor.py
> +        credits_snapshot.to_csv(
This should also upload to s3.

2025-01-14 21:12 UTC, QuanMPhm commented
I have rebased the PR

2025-01-15 14:48 UTC, QuanMPhm commented on process_report/processors/prepayment_processor.py
> +        credits_snapshot.to_csv(
The Credits snapshot will now to uploaded to `f"Invoices/{self.invoice_month}/NERC_Prepaid_Group-Credits-{self.invoice_month}.csv"` and the archive location `f"Invoices/{self.invoice_month}/Archive/NERC_Prepaid_Group-Credits-{self.invoice_month} {util.get_iso8601_time()}.csv"`

2025-02-25 16:45 UTC, QuanMPhm commented
The PR has been rebased

2025-02-26 13:12 UTC, joachimweyl commented
@QuanMPhm please re-request review after you rebase.

2025-02-26 13:29 UTC, QuanMPhm commented
@joachimweyl I don't see a button to allow a re-review yet :P I guess, @knikolla @naved001 @hakasapl Any opinions?

2025-02-26 17:51 UTC, knikolla reviewed
Stylistic and consistency comments. Otherwise looks good.

2025-02-26 17:51 UTC, knikolla commented on process_report/processors/prepayment_processor.py
> +    export_NERC_credits: bool = True  # For testing purposes
`export_NERC_credits` is inconsistently capitalized, should be `export_nerc_credits`.

2025-02-26 17:51 UTC, knikolla commented on process_report/processors/prepayment_processor.py
> +    @property
I usually try to have the following order for things defined in a class.

1. attributes
2. properties
3. methods

This makes it easier to find out where things are defined, so please move the properties after the attributes.

2025-02-26 17:51 UTC, knikolla commented on process_report/processors/prepayment_processor.py
> +    def CREDITS_SNAPSHOT_S3_FILEPATH(self):
While you could argue that these are all constants and therefore should be all caps, please don't.

2025-02-26 19:11 UTC, QuanMPhm commented on process_report/processors/prepayment_processor.py
> +    def CREDITS_SNAPSHOT_S3_FILEPATH(self):
I have repositioned and removed the capitalization on the properties.

2025-02-26 19:22 UTC, knikolla requested changes

2025-02-26 19:22 UTC, knikolla commented on process_report/processors/prepayment_processor.py
> +            self.CREDITS_SNAPSHOT_FILEPATH, self.CREDITS_SNAPSHOT_S3_FILEPATH
you changed the capitalization, but didn't change the capitalization of where they are used.

2025-02-27 01:54 UTC, knikolla reviewed
I don't like the idea of `Processors` exporting files into the `Invoices\<invoice_month>` folder, as that should be limited to only `Invoices`. 

Is this something that can be done in an `Invoice`?

2025-02-27 14:40 UTC, QuanMPhm commented
@knikolla Initially, I didn't want to create an invoice class for the NERC credits snapshot, since it wasn't technically an invoice. But now that you point it out, I'll make an `Invoice` class for it

2025-02-27 14:45 UTC, knikolla commented
> @knikolla Initially, I didn't want to create an invoice class for the NERC credits snapshot, since it wasn't technically an invoice. But now that you point it out, I'll make an `Invoice` class for it

@QuanMPhm Or alternatively, if it's not an Invoice, you could put it in a different folder. What is our purpose for exporting this file? What happens with it after export?

2025-02-27 14:53 UTC, QuanMPhm commented
From the [prepay scaffolding document](https://docs.google.com/document/d/1WetWwYkWevRrzDWDXVgVQ7s9CAqz5oSuIqyMBm0clNY/edit?tab=t.0#heading=h.xp16h61xthe0):
>NERC_Prepaid_Group-Credits-YYYY-MM.csv:
    Duplicate of Prepaid Group Credit
    This will provide the Prepaid credit information so that MGHPCC can add the cost to the bill
    MGHPCC does not differentiate on the PDF what is for what so it will show up under the NERC header, not important for codding just good for us to know
    Will be used to generate PDFs for Prepaid Group

@joachimweyl Let me know if this is still correct.

2025-02-27 15:03 UTC, knikolla commented
> This will provide the Prepaid credit information so that MGHPCC can add the cost to the bill

@QuanMPhm Sounds like it's an Invoice :) 

- It's not just a backup for archival purposes (similar to old PI files, etc)
- We give it out to the MGHPCC for their use

2025-02-27 16:59 UTC, QuanMPhm commented
@knikolla Could I have the prepay processor create the snapshot, and have the invoice class export it? That would make the code a bit less repetitive, but I understand if you think it might make the code look messier.

2025-02-27 21:05 UTC, QuanMPhm commented
I've decided to put everything into a new invoice class.

2025-02-27 21:16 UTC, knikolla approved these changes

2025-02-28 19:39 UTC, merged