PI invoices are now exported as PDFs
CCI-MOC/invoicing pull request #129
Opened 2024-12-31 04:51 UTC by QuanMPhm

Closes #84. This PR consists of the last commit.

This is currently in a draft state and will likely fail test cases. Apologizes for the current messiness. This draft demonstrates the main chunk of code involved in creating the PDF files. Two Python packages were crucial for this task, [Jinja](https://jinja.palletsprojects.com/en/stable/) and [Selenium](https://www.selenium.dev/documentation/)

2025-01-02 20:35 UTC, larsks requested changes
I think using `selenium` is overkill here. You can drive chrome's print-to-pdf functionality directly from the command line:

```
google-chrome --headless --print-to-pdf=output.pdf --no-pdf-header-footer document.html
```

This takes a single `subprocess.run()` call.

2025-01-02 21:27 UTC, larsks commented on process_report/invoices/pi_specific_invoice.py
> +            os.remove(invoice_html_path)
Instead of manually cleaning up the temporary file, you could make more effective use of `tempfile.NamedTemporaryFile` here by passing an open file into your `_create_*` methods:

```
with tempfile.NamedTemporaryFile(mode='w', suffix='.html') as tempfd:
  _create_html_invoice(tempfd)
  _create_pdf_invoice(tempfd)
```

```
def _create_html_invoice(tempfd):
    environment = Environment(loader=FileSystemLoader(TEMPLATE_DIR_PATH))
    template = environment.get_template("pi_invoice.html")
    content = template.render(
        data=pi_dataframe,
    )

    tempfd.write(content)

    # You might need this to ensure the content is visible in the file.
    tempfd.flush()
```

And you would need similar changes in `_create_pdf_invoice`.

2025-01-09 21:59 UTC, QuanMPhm commented on process_report/invoices/pi_specific_invoice.py
> +            os.remove(invoice_html_path)
@larsks  It turns out I did need to flush it. Thank you!

2025-01-09 22:06 UTC, QuanMPhm commented
@larsks I have removed the `selenium` dependancy and followed your approach. However, know I have a question regarding the unit test...

@larsks @knikolla The unit test failed because it did not find the chromium binary. I should change the github action file to install Chrome, or just I mock the `subprocess.run()` call to just write a pdf file?

2025-01-17 15:07 UTC, knikolla commented
> @larsks @knikolla The unit test failed because it did not find the chromium binary. Should I change the github action file to install Chrome, or should I just mock the `subprocess.run()` call to just write a pdf file?

Mock `os.path.exists` and `subprocess.run` and verify that it was called with the parameters you expected it to be called with.

2025-01-17 15:14 UTC, larsks commented
> @larsks @knikolla The unit test failed because it did not find the chromium binary. Should I change the github action file to install Chrome, or should I just mock the `subprocess.run()` call to just write a pdf file?

*Unit* tests shouldn't have external dependencies, which means you should mock out `subprocess.run`. 

It might be nice to have an integration test that calls out to chrome; this would ensure that our chrome command line is valid. If @knikolla agrees that's a good idea, that could be a future pull request.

2025-01-17 15:25 UTC, knikolla commented
> > @larsks @knikolla The unit test failed because it did not find the chromium binary. Should I change the github action file to install Chrome, or should I just mock the `subprocess.run()` call to just write a pdf file?
> 
> _Unit_ tests shouldn't have external dependencies, which means you should mock out `subprocess.run`.
> 
> It might be nice to have an integration test that calls out to chrome; this would ensure that our chrome command line is valid. If @knikolla agrees that's a good idea, that could be a future pull request.

Considering the rapid pace of chrome development and inability to rely on semantic versioning as they bump the major version number too often, I think it's worth having a test in the future that verifies that the command line arguments that we're passing are still accepted by the current version of chrome.

For the purposes of this PR, a unit test is enough.

2025-01-18 04:32 UTC, QuanMPhm commented
I have created a new issue to create the integration test at #145. I have also implemented all feedback so far.

2025-01-22 15:48 UTC, larsks commented on process_report/invoices/pi_specific_invoice.py
> +                return "$" + str(data)
You don't release need the `else` clause here, and prefer f-strings over string concatenation:

```suggestion
            return f"${data}"
```

But see my comment later on about whether or not we even need this function.

2025-01-22 15:48 UTC, larsks commented on process_report/invoices/pi_specific_invoice.py
> +        sum_columns_list = list()
In general, prefer `[]` over `list()` to initialize list variables:

```suggestion
        column_sums = []
        sum_columns_list = []
```

2025-01-22 15:48 UTC, larsks commented on process_report/invoices/pi_specific_invoice.py
> +                "CHROME_BIN_PATH", "usr/bin/chromium"
Should this actually be `/usr/bin/chromium`?

```suggestion
                "CHROME_BIN_PATH", "/usr/bin/chromium"
```

2025-01-22 15:48 UTC, larsks commented on process_report/invoices/pi_specific_invoice.py
> +                    "file://" + temp_fd_name,
Prefer an f-string (especially since you're using this syntax just a few lines earlier):

```suggestion
                    f"file://{temp_fd_name}",
```

2025-01-22 15:48 UTC, larsks commented on process_report/invoices/pi_specific_invoice.py
>              os.mkdir(self.name)
You can simplify this using `os.makedirs`:

```suggestion
        os.makedirs(self.name, exist_ok=True)
```

2025-01-22 15:48 UTC, larsks commented on process_report/invoices/pi_specific_invoice.py
> +                )
The `add_dollar_sign` function is so trivial, and we're only calling it once, so it might be better to replace it with a lambda function:

```suggestion
                pi_projects[column_name] = pi_projects[column_name].apply(
                    lambda data: data if pandas.isna(data) else f"${data}"
                )
```

2025-01-22 15:48 UTC, larsks commented on process_report/tests/unit/invoices/test_pi_specific_invoice.py
> +                return "$" + str(data)
(See my earlier comment about this function.)

2025-01-22 15:48 UTC, larsks commented on process_report/tests/unit/invoices/test_pi_specific_invoice.py
> +                self.assertTrue(answer_arg in chrome_arglist[0])
I would be more constrained in your check:

```suggestion
            self.assertTrue(answer_arglist == chrome_arglist[0][:-1])
```

2025-01-22 15:48 UTC, larsks commented on process_report/tests/unit/invoices/test_pi_specific_invoice.py
> +        output_dir = tempfile.TemporaryDirectory()
We don't need to create a temporary directory -- because we're mocking out `subprocess.run`, we never create any output.

You can do this instead:

```
        pi_inv = test_utils.new_pi_specific_invoice(
            "/fakedir", invoice_month, data=test_invoice
        )
        pi_inv.process()
        pi_inv.export()
        pi_pdf_1 = f"/fakedir/BU_PI1_{invoice_month}.pdf"
        pi_pdf_2 = f"/fakedir/HU_PI2_{invoice_month}.pdf"
```

2025-01-22 15:48 UTC, larsks commented on process_report/tests/unit/invoices/test_pi_specific_invoice.py
> +            group_name = [None for _ in range(len(pi))]
You can write instead:

```suggestion
            group_name = [None] * len(pi)
```

Compare:

```
>>> pi=[1,2,3,4,5]
>>> [None for _ in range(len(pi))]
[None, None, None, None, None]
>>> [None] * len(pi)
[None, None, None, None, None]
```

2025-01-22 15:48 UTC, larsks commented on process_report/invoices/pi_specific_invoice.py
> +                    f"Chrome binary does not exist at {chrome_binary_location}. Make sure the env var CHROME_BIN_PATH is set correctly or that Google Chrome is installed"
The message directs the user to ensure that Google Chrome is installed, but the code defaults to Chromium (which could lead to the situation in which Google Chrome is installed but the user still receives this error message). It makes more sense to replace `or` with `and`:

```suggestion
                    f"Chrome binary does not exist at {chrome_binary_location}. Make sure that Google Chrome is installed and the environment variable CHROME_BIN_PATH is set correctly."
```

2025-02-07 19:47 UTC, joachimweyl commented
@QuanMPhm is this ready to merge?

2025-02-19 21:18 UTC, naved001 approved these changes

2025-02-20 20:32 UTC, merged